name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build with dotnet
      run: dotnet build Fingerprinty.Test.NetCore --configuration Debug -f netcoreapp3.1
    - name: Test with dotnet
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput='./coverage/'
    - name: Upload coverage details
      uses: actions/upload-artifact@v1
      with:
        name: coverage-ubuntu
        path: ./Fingerprinty.Test.NetCore/coverage

  build-windows-netcore:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build with dotnet
      run: dotnet build Fingerprinty.Test.NetCore --configuration Debug -f netcoreapp3.1
    - name: Test with dotnet
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutput='./coverage/'
    - name: Upload coverage details
      uses: actions/upload-artifact@v1
      with:
        name: coverage-windows
        path: ./Fingerprinty.Test.NetCore/coverage

  build-windows-netframework:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
    - name: Restore NuGet Packages
      run: nuget restore Fingerprinty.sln
    - name: Build
      run: msbuild Fingerprinty.sln /p:Configuration=Debug
    - name: Run Tests
      run: vstest.console.exe .\Fingerprinty.Test.NetCore\bin\Debug\Fingerprinty.Test.NetCore.dll