name: Create NuGet package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-package:

    runs-on: ubuntu-latest
    env: 
      SHORTSHA: ${{$(git rev-parse --short=7 ${{ github.sha }})}}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Pack with dotnet
      run: dotnet pack Fingerprinty --configuration Release -o CreatedPackages --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --version-suffix $SHORTSHA
    - name: Upload package
      uses: actions/upload-artifact@v1
      with:
        name: nuget_package
        path: CreatedPackages
